### ISSUE TITLE
Can't run plugin

### ISSUE THREAD

**Issue by mad73923** [gotify/plugin-template#8]
I'm on https://github.com/mad73923/prometheus-gotify-plugin/commit/f4a6f4b6ba59f149b807f2441a844ab14d02ae5a and can't run the basic plugin.
I get the following output:
```
gotify_1  | Starting Gotify version 2.0.23@2021-06-19-10:08:25
gotify_1  | fatal error: runtime: no plugin module data
gotify_1  | 
gotify_1  | goroutine 1 [running]:
gotify_1  | runtime.throw(0x1002c13, 0x1e)
gotify_1  | 	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0005654e0 sp=0xc0005654b0 pc=0x6b67d2
gotify_1  | plugin.lastmoduleinit(0xc0001114a0, 0x1001, 0x1001, 0xc000118178, 0x7f8c38000eb0)
gotify_1  | 	/usr/local/go/src/runtime/plugin.go:20 +0xb50 fp=0xc0005655d8 sp=0xc0005654e0 pc=0x6e8830
gotify_1  | plugin.open(0xc00039e200, 0x3d, 0x3, 0xc00039e200, 0x40)
gotify_1  | 	/usr/local/go/src/plugin/plugin_dlopen.go:77 +0x4ef fp=0xc000565850 sp=0xc0005655d8 pc=0xd2258f
gotify_1  | plugin.Open(...)
gotify_1  | 	/usr/local/go/src/plugin/plugin.go:32
gotify_1  | github.com/gotify/server/v2/plugin.(*Manager).loadPlugins(0xc000120300, 0xc000465d40, 0xc, 0x1589380, 0xc000118160)
gotify_1  | 	/proj/plugin/manager.go:230 +0x1f1 fp=0xc000565940 sp=0xc000565850 pc=0xd265d1
gotify_1  | github.com/gotify/server/v2/plugin.NewManager(0x1589380, 0xc000118160, 0xc000465d40, 0xc, 0xc0001202c0, 0x156e940, 0xc000120280, 0x6e2501, 0x0, 0x0)
gotify_1  | 	/proj/plugin/manager.go:86 +0x197 fp=0xc000565a90 sp=0xc000565940 pc=0xd25657
gotify_1  | github.com/gotify/server/v2/router.Create(0xc000118160, 0xc000500990, 0xc0003d6c00, 0xe, 0xc000465c78)
gotify_1  | 	/proj/router/router.go:44 +0x78b fp=0xc000565ec0 sp=0xc000565a90 pc=0xd9da6b
gotify_1  | main.main()
gotify_1  | 	/proj/app.go:51 +0x388 fp=0xc000565f88 sp=0xc000565ec0 pc=0xdcbdc8
gotify_1  | runtime.main()
gotify_1  | 	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc000565fe0 sp=0xc000565f88 pc=0x6b9256
gotify_1  | runtime.goexit()
gotify_1  | 	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000565fe8 sp=0xc000565fe0 pc=0x6ed701
gotify_1  | 
gotify_1  | goroutine 18 [select]:
gotify_1  | database/sql.(*DB).connectionOpener(0xc0004e7e10, 0x157e8b8, 0xc000518740)
gotify_1  | 	/usr/local/go/src/database/sql/sql.go:1133 +0xb5
gotify_1  | created by database/sql.OpenDB
gotify_1  | 	/usr/local/go/src/database/sql/sql.go:740 +0x12a
gotify_1  | 
gotify_1  | goroutine 8 [chan receive]:
gotify_1  | github.com/gotify/server/v2/plugin.NewManager.func1(0xc000120300, 0x1589380, 0xc000118160, 0x156e940, 0xc000120280)
gotify_1  | 	/proj/plugin/manager.go:69 +0xf2
gotify_1  | created by github.com/gotify/server/v2/plugin.NewManager
gotify_1  | 	/proj/plugin/manager.go:67 +0x16c
gotify-plugin-template_gotify_1 exited with code 2
```

**Comment by jmattheis** [comment]
Oops, sorry. I've must have overlooked this. I've tested the current plugin-api repo against gotify/server v2.4.0, and it works fine there.
